/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppInbodyRouteImport } from './routes/_app/inbody'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as WorkoutSessionIdRouteImport } from './routes/workout.$sessionId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsExercisesRouteImport } from './routes/_app/settings.exercises'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppInbodyRoute = AppInbodyRouteImport.update({
  id: '/inbody',
  path: '/inbody',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutSessionIdRoute = WorkoutSessionIdRouteImport.update({
  id: '/workout/$sessionId',
  path: '/workout/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsExercisesRoute = AppSettingsExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/history': typeof AppHistoryRoute
  '/inbody': typeof AppInbodyRoute
  '/progress': typeof AppProgressRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/workout/$sessionId': typeof WorkoutSessionIdRoute
  '/settings/exercises': typeof AppSettingsExercisesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/history': typeof AppHistoryRoute
  '/inbody': typeof AppInbodyRoute
  '/progress': typeof AppProgressRoute
  '/workout/$sessionId': typeof WorkoutSessionIdRoute
  '/': typeof AppIndexRoute
  '/settings/exercises': typeof AppSettingsExercisesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/recover': typeof RecoverRoute
  '/signup': typeof SignupRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/inbody': typeof AppInbodyRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/workout/$sessionId': typeof WorkoutSessionIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/exercises': typeof AppSettingsExercisesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/recover'
    | '/signup'
    | '/history'
    | '/inbody'
    | '/progress'
    | '/settings'
    | '/workout/$sessionId'
    | '/settings/exercises'
    | '/api/auth/$'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/recover'
    | '/signup'
    | '/history'
    | '/inbody'
    | '/progress'
    | '/workout/$sessionId'
    | '/'
    | '/settings/exercises'
    | '/api/auth/$'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/recover'
    | '/signup'
    | '/_app/history'
    | '/_app/inbody'
    | '/_app/progress'
    | '/_app/settings'
    | '/workout/$sessionId'
    | '/_app/'
    | '/_app/settings/exercises'
    | '/api/auth/$'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RecoverRoute: typeof RecoverRoute
  SignupRoute: typeof SignupRoute
  WorkoutSessionIdRoute: typeof WorkoutSessionIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbody': {
      id: '/_app/inbody'
      path: '/inbody'
      fullPath: '/inbody'
      preLoaderRoute: typeof AppInbodyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/$sessionId': {
      id: '/workout/$sessionId'
      path: '/workout/$sessionId'
      fullPath: '/workout/$sessionId'
      preLoaderRoute: typeof WorkoutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/exercises': {
      id: '/_app/settings/exercises'
      path: '/exercises'
      fullPath: '/settings/exercises'
      preLoaderRoute: typeof AppSettingsExercisesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsExercisesRoute: typeof AppSettingsExercisesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsExercisesRoute: AppSettingsExercisesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppInbodyRoute: typeof AppInbodyRoute
  AppProgressRoute: typeof AppProgressRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppInbodyRoute: AppInbodyRoute,
  AppProgressRoute: AppProgressRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RecoverRoute: RecoverRoute,
  SignupRoute: SignupRoute,
  WorkoutSessionIdRoute: WorkoutSessionIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
